sudo: required
services:
  - docker

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    test -e Gemfile || cat <<EOF > Gemfile
    source 'https://rubygems.org'
    gem 'rake'
    gem 'test-kitchen'
    gem 'kitchen-docker'
    gem 'kitchen-vagrant'
    gem 'kitchen-inspec'
    gem 'inspec'
    gem 'kitchen-salt', :git => 'https://github.com/salt-formulas/kitchen-salt.git'
  - bundle install

env:
  # - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc311 SUITE=single
  - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc311 SUITE=analytics
  - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc311 SUITE=control
  # - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc311 SUITE=cluster
  # - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc311 SUITE=tor
  - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc311 SUITE=vrouter
  # - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc323 SUITE=single
  - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc323 SUITE=analytics
  - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc323 SUITE=control
  # - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc323 SUITE=cluster
  # - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc323 SUITE=tor
  - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc323 SUITE=vrouter
  # - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc323 SUITE=single
  - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc323 SUITE=analytics
  - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc323 SUITE=control
  # - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc323 SUITE=cluster
  # - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc323 SUITE=tor
  - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc323 SUITE=vrouter
  # - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc40 SUITE=single40
  - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc40 SUITE=analytics40
  - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc40 SUITE=control40
  # - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc40 SUITE=cluster40
  # - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc40 SUITE=tor40
  - PLATFORM=trevorj/salty-whales:trusty OC_REPO=oc40 SUITE=vrouter40
  # - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc40 SUITE=single40
  - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc40 SUITE=analytics40
  - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc40 SUITE=control40
  # - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc40 SUITE=cluster40
  # - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc40 SUITE=tor40
  - PLATFORM=trevorj/salty-whales:xenial OC_REPO=oc40 SUITE=vrouter40

before_script:
  - set -o pipefail
  - make test | tail

script:
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml bundle exec kitchen test -t tests/integration

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6123573504759330786b
    on_success: change  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    on_cancel: never    # options: [always|never|change] default: always
    on_error: never    # options: [always|never|change] default: always
  email: false
